---
jekyll: gtome-new-indexer
settings:
  name: Cloud Manager 3.6
  nss_product: OnCommand Cloud Manager
  downlevel: true
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-tw
sidebar:
  entries:
  - title: Cloud Manager 3.6 文档
    url: "/index.html"
  - title: 发行说明
    entries:
    - title: 云管理器
      entries:
      - title: 新增功能
        url: "/reference_new_occm.html"
      - title: 已知问题
        url: "/reference_issues.html"
      - title: 已知限制
        url: "/reference_limitations.html"
    - title: Cloud Volumes ONTAP
      url: https://docs.netapp.com/us-en/cloud-volumes-ontap/
  - title: 概念
    entries:
    - title: 产品概述
      url: "/concept_overview.html"
    - title: NetApp Cloud Central
      url: "/concept_cloud_central.html"
    - title: 帐户和权限
      url: "/concept_accounts_and_permissions.html"
    - title: 存储
      entries:
      - title: 概述
        url: "/concept_storage.html"
      - title: 数据分层
        url: "/concept_data_tiering.html"
      - title: 存储管理
        url: "/concept_storage_management.html"
      - title: WORM 存储
        url: "/concept_worm.html"
    - title: 高可用性对
      entries:
      - title: AWS 中的 HA 对
        url: "/concept_ha.html"
      - title: Azure 中的 HA 对
        url: "/concept_ha_azure.html"
    - title: 评估
      url: "/concept_evaluating.html"
    - title: 许可
      url: "/concept_licensing.html"
    - title: 安全性
      url: "/concept_security.html"
    - title: 性能
      url: "/concept_performance.html"
  - title: 入门
    entries:
    - title: 部署概述
      url: "/reference_deployment_overview.html"
    - title: AWS 入门
      url: "/task_getting_started_aws.html"
    - title: Azure 入门
      url: "/task_getting_started_azure.html"
    - title: 设置云管理器
      entries:
      - title: 添加云提供商帐户
        url: "/task_adding_cloud_accounts.html"
      - title: 添加 NetApp 支持站点帐户
        url: "/task_adding_nss_accounts.html"
      - title: 安装 HTTPS 证书
        url: "/task_installing_https_cert.html"
      - title: 设置用户和租户
        url: "/task_setting_up_users_tenants.html"
      - title: 设置 AWS KMS
        url: "/task_setting_up_kms.html"
    - title: 网络要求
      entries:
      - title: 云管理器
        url: "/reference_networking_cloud_manager.html"
      - title: 适用于 AWS 的 Cloud Volumes ONTAP
        url: "/reference_networking_aws.html"
      - title: 设置 AWS 传输网关
        url: "/task_setting_up_transit_gateway.html"
      - title: 适用于 Azure 的 Cloud Volumes ONTAP
        url: "/reference_networking_azure.html"
    - title: 其他部署选项
      entries:
      - title: 云管理器主机要求
        url: "/reference_cloud_mgr_reqs.html"
      - title: 在 Linux 主机上安装 Cloud Manager
        url: "/task_installing_linux.html"
      - title: 从 AWS Marketplace 部署 Cloud Manager
        url: "/task_launching_aws_mktp.html"
      - title: 从 Azure Marketplace 部署 Cloud Manager
        url: "/task_launching_azure_mktp.html"
      - title: 在 Azure Gov 区域部署 Cloud Manager
        url: "/task_installing_azure_gov.html"
      - title: 在德国 Azure 地区部署 Cloud Manager
        url: "/task_installing_azure_germany.html"
      - title: AWS C2S 环境入门
        url: "/media/c2s.pdf"
  - title: 部署 Cloud Volumes ONTAP
    entries:
    - title: 开始之前
      url: "/reference_before.html"
    - title: 登录到 Cloud Manager
      url: "/task_logging_in.html"
    - title: 规划配置
      url: "/task_planning_your_config.html"
    - title: 在 AWS 中的 Cloud Volumes ONTAP 上启用 Flash Cache
      url: "/task_enabling_flash_cache.html"
    - title: 在 AWS 中启动 Cloud Volumes ONTAP
      url: "/task_deploying_otc_aws.html"
    - title: 在 Azure 中启动 Cloud Volumes ONTAP
      url: "/task_deploying_otc_azure.html"
    - title: 注册按需购买的系统
      url: "/task_registering.html"
    - title: 设置 Cloud Volumes ONTAP
      url: "/task_setting_up_ontap_cloud.html"
  - title: 配置存储
    entries:
    - title: 创建卷、聚合和 LUN
      url: "/task_provisioning_storage.html"
    - title: 将非活动数据分层到对象存储
      url: "/task_tiering.html"
    - title: 使用 Cloud Volumes ONTAP 作为永久性存储
      url: "/task_connecting_kubernetes.html"
    - title: 使用 NetApp 卷加密对卷进行加密
      url: "/task_encrypting_volumes.html"
    - title: 管理现有存储
      url: "/task_managing_storage.html"
    - title: 从卷视图配置 NFS 卷
      entries:
      - title: 更改为卷视图
        url: "/task_changing_volume_view.html"
      - title: 创建和装入 NFS 卷
        url: "/task_provisioning_volume_view.html"
      - title: 管理 NFS 卷
        url: "/task_managing_volume_view.html"
  - title: 跨混合云管理数据
    entries:
    - title: 发现和管理 ONTAP 集群
      url: "/task_discovering_ontap.html"
    - title: 将数据复制到云中或从云中复制数据
      url: "/task_replicating_data.html"
    - title: 将数据同步到 AWS S3
      url: "/task_syncing_s3.html"
  - title: 管理 Cloud Volumes ONTAP
    entries:
    - title: 连接到 Cloud Volumes ONTAP
      url: "/task_connecting_to_otc.html"
    - title: 正在更新软件
      url: "/task_updating_ontap_cloud.html"
    - title: 修改系统配置
      url: "/task_modifying_ontap_cloud.html"
    - title: 停止和启动系统
      url: "/task_managing_state.html"
    - title: 监控 AWS 成本
      url: "/task_monitoring_costs.html"
    - title: 改进勒索软件保护
      url: "/task_protecting_ransomware.html"
    - title: 添加现有系统
      url: "/task_adding_ontap_cloud.html"
    - title: 删除系统
      url: "/task_deleting_working_env.html"
  - title: 管理云管理器
    entries:
    - title: 更新 Cloud Manager
      url: "/task_updating_cloud_manager.html"
    - title: 备份和还原
      url: "/task_backing_up_restoring.html"
    - title: 删除工作环境
      url: "/task_removing.html"
    - title: 编辑用户帐户
      url: "/task_editing_users.html"
    - title: 配置代理设置
      url: "/task_configuring_proxy.html"
    - title: 续订 HTTPS 证书
      url: "/task_renewing_cert.html"
    - title: 卸载 Cloud Manager
      url: "/task_uninstalling.html"
  - title: API 和自动化
    entries:
    - title: API 开发人员指南
      url: https://docs.netapp.com/us-en/occm/api.html
    - title: 自动化示例
      url: "/reference_infrastructure_as_code.html"
  - title: 参考
    entries:
    - title: Cloud Central 集成常见问题解答
      url: "/reference_integration_faq.html"
    - title: 支持的 Cloud Volumes ONTAP 配置
      url: https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_supported_configs_95.html
    - title: 支持的区域
      url: https://cloud.netapp.com/cloud-volumes-global-regions
    - title: AWS 的安全组规则
      url: "/reference_security_groups.html"
    - title: Azure 的安全组规则
      url: "/reference_security_groups_azure.html"
    - title: 权限
      url: "/reference_permissions.html"
    - title: 默认配置
      url: "/reference_default_configs.html"
    - title: 用户角色
      url: "/reference_user_roles.html"
    - title: 相关链接
      url: "/reference_additional_info.html"
  - title: 法律声明
    url: "/reference_legal_notices.html"
