---
sidebar: sidebar 
permalink: reference_additional_info.html 
keywords: community, forums, help, support, videos, policies, json, api, ontap, release notes, bugs, limitations, known issues, permissions, apis 
summary: 您可以通过各种资源（包括视频、论坛和支持）获得有关 Cloud Manager 和 Cloud Volumes ONTAP 的帮助和详细信息。 
---
= 从何处获取帮助和查找更多信息
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以通过各种资源（包括视频、论坛和支持）获得有关 Cloud Manager 和 Cloud Volumes ONTAP 的帮助和详细信息。

* https://["适用于 Cloud Manager 和 Cloud Volumes ONTAP 的视频"^]
+
观看视频、了解如何在 AWS 和 Azure 中部署和管理 Cloud Volumes ONTAP 、以及如何在混合云中复制数据。

* http://["云管理器策略"^]
+
下载 JSON 文件、其中包括 Cloud Manager 在 AWS 和 Azure 中执行操作所需的权限。

* link:api.html["Cloud Manager API 开发人员指南"^]
+
阅读 API 概述、如何使用这些 API 的示例以及 API 参考。

* Cloud Volumes ONTAP 培训
+
** https://["Cloud Volumes ONTAP 基础知识"^]
** https://["适用于 Azure 的 Cloud Volumes ONTAP 部署和管理"^]


* 技术报告
+
** https://["NetApp 技术报告 4383 ：使用应用程序工作负载在 Amazon Web Services 中对 Cloud Volumes ONTAP 进行性能特征描述"^]
** https://["NetApp 技术报告 4671 ： Azure 中的 Cloud Volumes ONTAP 的性能特征与应用程序工作负载"^]


* https://["Cloud Volumes ONTAP 9 SVM 灾难恢复准备快速指南"^]
+
介绍如何快速配置目标 SVM 以准备灾难恢复。

* https://["Cloud Volumes ONTAP 9 SVM 灾难恢复快速指南"^]
+
介绍如何在发生灾难后快速激活目标 SVM 、然后重新激活源 SVM 。

* http://["ONTAP 9 文档中心"^]
+
访问 ONTAP 的产品文档、它可以帮助您使用 Cloud Volumes ONTAP 。

* https://["NetApp Cloud Volumes ONTAP 支持"^]
+
访问支持资源以获得有关 Cloud Volumes ONTAP 的帮助和故障排除问题。

* https://["NetApp 社区：云数据服务"^]
+
与同行联系、提出问题、交换意见、查找资源并共享最佳实践。

* http://["NetApp Cloud Central"^]
+
查找有关适用于云的其他 NetApp 产品和解决方案的信息。

* http://["NetApp 产品文档"^]
+
在 NetApp 产品文档中搜索说明、资源和答案。


